x-logging: &default-logging
  options:
    max-size: "50m"
    max-file: "2"
    compress: "true"
  driver: local
  
services:
  app:
    build:
      context: .               # Use the current directory as the build context
    ports:
      - "6906:5173"            
    container_name: tic-tac-toe-react